### ISSUE TITLE
What is this import?

### ISSUE THREAD

**Issue by djdrakos** [armaBurton/from-scratch-gitty#4]
https://github.com/armaBurton/from-scratch-gitty/blob/36c3cc07d5d01d7ca0062372a1643f4d226bc7ad/lib/controllers/gweets.js#L2

Not sure you need this.

**Comment by armaBurton** [comment]
Probably the same as the other issue. They get auto-installed and I neglect to remove them.

removed both: 
```
const res = require('express/lib/response');
const jwt = require('jsonwebtoken');
```
