### ISSUE TITLE
What is this import?

### ISSUE THREAD

**Issue by djdrakos** [armaBurton/from-scratch-gitty#5]
https://github.com/armaBurton/from-scratch-gitty/blob/36c3cc07d5d01d7ca0062372a1643f4d226bc7ad/lib/controllers/auth.js#L2

Not sure you need this.

**Comment by armaBurton** [comment]
That was accidentally added because I had: (req, rez) instead of (req, res) and the **_res_**.clearCookie(...) was undefined.

```
  .delete('/logout', (req, **_rez_**) => {
    **_res_**
      .clearCookie(process.env.COOKIE_NAME)
      .json({ success: true, message: 'Signed out successfully!' });
  });
```

fixed now.
