### ISSUE TITLE
Refactor logic in if statement

### ISSUE THREAD

**Issue by djdrakos** [armaBurton/from-scratch-gitty#7]
https://github.com/armaBurton/from-scratch-gitty/blob/36c3cc07d5d01d7ca0062372a1643f4d226bc7ad/lib/models/GithubUser.js#L37

Try `if (!rows[0]) `. The logic evaluates to the same result, and is cleaner code, since the expression matches what you're returning from the function.

**Comment by armaBurton** [comment]
done
